delete from Companies
delete from CompanyEmployeesReservationsDetails
delete from CompanyReservationDetails
delete from CompanyReservations
delete from Constants
delete from Customers
delete from Discounts
delete from Dishes
delete from Employees
delete from IndividualReservations
delete from IndividualReservationsDetails
delete from LifeLongDiscounts
delete from LifeLongDiscountsHist
delete from Menu
delete from OrderDetails
delete from Orders
delete from Reservations
delete from RestaurantEmployees
delete from SingleUseDiscountsHist
delete from SingleUseDiscounts
delete from TableHist
delete from Tables
delete from Categories
delete from Cities
delete from Regions
delete from Countries
delete from Clients